packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

# ============================================
# PNPM CATALOG - Centralized Version Management
# ============================================
# Use: "style-dictionary": "catalog:"
# Docs: https://pnpm.io/catalogs

catalog:
  # ============================================
  # BUILD TOOLS
  # ============================================
  rollup: ^4.52.3
  vite: ^5.4.11              # Upgraded from 4.5.14 (required by vitest)
  typescript: ^5.9.3
  tslib: ^2.8.1
  turbo: ^2.3.3
  
  # ============================================
  # DESIGN TOKENS
  # ============================================
  style-dictionary: ^3.9.2   # Latest v3 (v5 is beta)
  nodemon: ^3.1.11
  
  # ============================================
  # REACT & TESTING
  # ============================================
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  '@testing-library/react': ^16.1.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/user-event': ^14.6.1
  vitest: ^2.1.9             # Aligned with @vitest/* packages
  '@vitest/ui': ^2.1.9       # Matched with vitest
  '@vitest/coverage-v8': ^2.1.9
  '@vitest/browser': ^2.1.9  # Matched with vitest
  jsdom: ^25.0.1
  
  # ============================================
  # STORYBOOK (v9 - Latest Stable)
  # ============================================
  # Note: Migrated to v9 for consistency
  storybook: ^9.1.12         # Upgraded from mixed v8/v9
  '@storybook/react': ^9.1.12
  '@storybook/react-vite': ^9.1.12
  '@storybook/addon-essentials': ^9.1.12  # Upgraded from v8
  '@storybook/addon-interactions': ^9.1.12 # Upgraded from v8
  '@storybook/addon-a11y': ^9.1.12
  '@storybook/addon-docs': ^9.1.12
  '@storybook/addon-controls': ^9.1.12
  '@storybook/addon-vitest': ^9.1.12
  '@chromatic-com/storybook': ^3.2.2
  
  # ============================================
  # ROLLUP PLUGINS
  # ============================================
  '@rollup/plugin-node-resolve': ^15.3.1
  '@rollup/plugin-commonjs': ^28.0.1
  '@rollup/plugin-typescript': ^12.3.0
  'rollup-plugin-peer-deps-external': ^2.2.4
  'rollup-plugin-postcss': ^4.0.2
  
  # ============================================
  # CSS & STYLING
  # ============================================
  postcss: ^8.4.49
  autoprefixer: ^10.4.20
  'postcss-nesting': ^13.0.1
  sass: ^1.83.4
  'sass-embedded': ^1.83.4
  
  # ============================================
  # LINTING & FORMATTING
  # ============================================
  '@typescript-eslint/parser': ^8.18.2
  'eslint-plugin-import': ^2.31.0
  'eslint-plugin-storybook': ^0.11.1
  
  # ============================================
  # UTILITIES
  # ============================================
  classnames: ^2.5.1
  glob: ^11.0.0
  tsx: ^4.19.2
  terser: ^5.37.0
  '@types/node': ^22.10.5
  '@types/classnames': ^2.3.1
  
  # ============================================
  # PLAYWRIGHT & E2E
  # ============================================
  '@playwright/test': ^1.49.1
  playwright: ^1.49.1
  
  # ============================================
  # ACCESSIBILITY
  # ============================================
  'axe-core': ^4.10.2
  'vitest-axe': ^1.0.0
